import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { adminApiClient } from '../api/client';
import type { InternationalTestDto, InternationalTestVersionDto } from '@manaratak/domain';

type Kind='SESSION'|'CENTER'|'REQUIREMENT'|'POLICY'|'EQUIVALENCY';
const fields:Record<Kind,string[]>={SESSION:['versionId','title','sessionCode','registrationOpensAt','registrationClosesAt','startsAt','endsAt','timezone','status'],CENTER:['displayName','centerCode','countryIso2Code','cityName','address','officialUrl','status'],REQUIREMENT:['versionId','requirementType','title','description','isMandatory'],POLICY:['versionId','policyType','title','description','sourceUrl','effectiveFrom','effectiveTo'],EQUIVALENCY:['sourceScale','sourceValue','targetScale','targetValue','confidence']};
const labels:Record<string,string>={versionId:'نسخة المصدر',title:'العنوان',sessionCode:'رمز الدورة',registrationOpensAt:'بداية التسجيل',registrationClosesAt:'نهاية التسجيل',startsAt:'البداية',endsAt:'النهاية',timezone:'المنطقة الزمنية',status:'الحالة',displayName:'اسم المركز',centerCode:'رمز المركز',countryIso2Code:'رمز الدولة',cityName:'المدينة والعنوان',address:'العنوان',officialUrl:'الرابط الرسمي',requirementType:'نوع المتطلب',description:'التفاصيل',isMandatory:'إلزامي',policyType:'نوع السياسة',sourceUrl:'رابط المصدر',effectiveFrom:'ساري من',effectiveTo:'ساري حتى',sourceScale:'مقياس المصدر',sourceValue:'قيمة المصدر',targetScale:'المقياس المقابل',targetValue:'القيمة المقابلة',confidence:'الثقة'};
export function InternationalTestGovernanceWorkspace({testId,isRtl,onSaved}:{testId:string;isRtl:boolean;onSaved:()=>void|Promise<void>}) {
  const [page,setPage]=useState(1);const [refresh,setRefresh]=useState(0);const [reason,setReason]=useState('');const [evidenceReference,setEvidenceReference]=useState('');
  const [versions,setVersions]=useState<InternationalTestVersionDto[]>([]);const [history,setHistory]=useState<any>();const [test,setTest]=useState<InternationalTestDto>();
  const [usage,setUsage]=useState<any>();const [usagePage,setUsagePage]=useState(1);const [timeline,setTimeline]=useState<any>();const [cursor,setCursor]=useState<string>();
  const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const submitting=useRef(false);
  const [kind,setKind]=useState<Kind>('SESSION');const [profile,setProfile]=useState<Record<string,string|number|boolean>>({});
  const [nameAr,setNameAr]=useState('');const [nameEn,setNameEn]=useState('');
  useEffect(()=>{const controller=new AbortController();setError('');
    Promise.all([adminApiClient.request<InternationalTestDto>(`/admin/international-tests/${testId}`,{signal:controller.signal}),adminApiClient.request<InternationalTestVersionDto[]>(`/admin/international-tests/${testId}/import-versions?page=${page}`,{signal:controller.signal}),adminApiClient.request<any>(`/admin/international-tests/${testId}/governance-history?page=${page}`,{signal:controller.signal})]).then(([owner,items,records])=>{if(!controller.signal.aborted){setTest(owner);setVersions(items);setHistory(records);}}).catch(err=>{if(!controller.signal.aborted)setError(err.message);});return()=>controller.abort();
  },[testId,page,refresh]);
  const command=async(path:string,body:object)=>{if(submitting.current)return;if(reason.trim().length<3){setError(isRtl?'أدخل سبب المراجعة.':'Enter a review reason.');return;}submitting.current=true;setBusy(true);setError('');setNotice('');try {await adminApiClient.request(`/admin/international-tests/${testId}/${path}`,{method:'POST',body:JSON.stringify({...body,reason})});setNotice(isRtl?'تم حفظ القرار.':'Decision saved.');await onSaved();setRefresh(n=>n+1);}catch(err){setError(err instanceof Error?err.message:'Unable to save');}finally{submitting.current=false;setBusy(false);}};
  useEffect(()=>{const controller=new AbortController();if(usage!==undefined)adminApiClient.request<any>(`/admin/international-tests/${testId}/usage?page=${usagePage}`,{signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setUsage(data);}).catch(err=>{if(!controller.signal.aborted)setError(err.message);});return()=>controller.abort();},[testId,usagePage]);
  const loadTimeline=async(next?:string)=>{try {const data=await adminApiClient.request<any>(`/admin/international-tests/${testId}/timeline${next?'?cursor='+encodeURIComponent(next):''}`);setTimeline(data);setCursor(data.nextCursor?JSON.stringify(data.nextCursor):undefined);}catch(err){setError(err instanceof Error?err.message:'Timeline unavailable');}};
  const profileKey=({SESSION:'sessions',CENTER:'centers',REQUIREMENT:'requirements',POLICY:'policies',EQUIVALENCY:'equivalencyMappings'} as const)[kind];
  return <section className="space-y-4 rounded-xl border p-4" dir={isRtl?'rtl':'ltr'}>
    <h3 className="font-bold">{isRtl?'المراجعة والاعتماد وسجل النشر':'Review, approval and publication history'}</h3>
    <label className="block">{isRtl?'سبب القرار':'Review reason'}<textarea className="w-full rounded border p-2" value={reason} onChange={e=>setReason(e.target.value)} /></label>
    {error&&<p role="alert" className="text-red-700">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <div className="flex flex-wrap gap-3">{[['verify-source','التحقق من المصدر','Verify source'],['mark-publishable','اعتماد النسخة','Approve candidate'],['publish','نشر النسخة المعتمدة','Publish approved candidate'],['revoke-source','سحب تحقق المصدر','Revoke source verification']].map(([path,ar,en])=><button type="button" disabled={busy} key={path} onClick={()=>void command(path,{})}>{isRtl?ar:en}</button>)}</div>
    <div className="flex gap-3">{[['READY_TO_REVIEW','إرسال للمراجعة','Submit for review'],['NEEDS_REVIEW','طلب تعديل','Request changes'],['REJECTED','رفض','Reject']].map(([status,ar,en])=><button type="button" disabled={busy} key={status} onClick={()=>void command('review-transition',{status})}>{isRtl?ar:en}</button>)}</div>
    {history?.freshness?.categories.map((item:any)=><p key={item.category}>{item.category}: {item.needsVerification?(isRtl?'يحتاج تحققًا حديثًا':'Needs fresh verification'):(isRtl?'ضمن الفترة':'Within review window')} ({item.days} {isRtl?'يوم':'days'})</p>)}
    <details><summary>{isRtl?'إزالة علاقة من المسودة':'Remove a draft relationship'}</summary>{(['COUNTRY','LANGUAGE','TAXONOMY','DEGREE'] as const).flatMap(kind=>{
      const key={COUNTRY:'countryRelationships',LANGUAGE:'languageRelationships',TAXONOMY:'academicTaxonomyRelationships',DEGREE:'degreeRelationships'}[kind];
      return ((test?.[key] as Array<Record<string,unknown>>|undefined)??[]).map(row=>{const referenceId=String(row.canonicalReferenceId??row.taxonomyNodeId??row.degreeLevelId??'');return <p key={`${kind}-${referenceId}-${row.relationshipType}`}>{kind} · {String(row.referenceCode??row.canonicalCode??referenceId)} · {String(row.relationshipType)}<button type="button" disabled={busy} onClick={()=>void command('remove-relationship',{kind,referenceId,relationshipType:row.relationshipType})}>{isRtl?'إزالة':'Remove'}</button></p>;});
    })}</details>
    <h4>{isRtl?'مراجعة أقسام المصدر':'Source block review'}</h4>
    <label>{isRtl?'مرجع الدليل أو الحقل المطابق':'Evidence or mapping reference'}<input className="w-full rounded border p-2" value={evidenceReference} onChange={e=>setEvidenceReference(e.target.value)} /></label>
    {versions.map(version=><article className="rounded border p-3" key={version.id}><h5>{version.sourceFileName??`#${version.versionNumber}`} · {version.status}</h5>{version.contentBlocks?.map(block=><div key={block.id} className="my-2 border-t p-2"><strong>{block.title??block.blockKey}</strong><p>{block.reviewStatus}</p><details><summary>{isRtl?'عرض المحتوى':'View content'}</summary><pre className="max-h-48 overflow-auto whitespace-pre-wrap">{block.content}</pre></details>{['APPROVED','IGNORED','MAPPED'].map(decision=><button className="mx-2" type="button" key={decision} disabled={busy||!version.sourceHash||version.status==='PUBLISHED'||version.status==='SUPERSEDED'} onClick={()=>void command('review-block',{versionId:version.id,sourceHash:version.sourceHash,blockId:block.id,decision,...(decision==='MAPPED'?{mappingReference:evidenceReference}:{})})}>{decision}</button>)}</div>)}</article>)}
    <div className="flex gap-3"><button type="button" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>{isRtl?'السابق':'Previous'}</button><span>{page}</span><button type="button" disabled={versions.length<25&&((history?.evidence?.length??0)<25)&&((history?.releases?.length??0)<25)} onClick={()=>setPage(p=>p+1)}>{isRtl?'التالي':'Next'}</button></div>
    <details><summary>{isRtl?'مراكز ومواعيد وسياسات الاختبار':'Centers, sessions and policies'}</summary><label>{isRtl?'نوع البيانات':'Profile section'}<select value={kind} onChange={e=>{setKind(e.target.value as Kind);setProfile({});}}>{Object.keys(fields).map(value=><option key={value}>{value}</option>)}</select></label>
      {(test?.[profileKey] as Array<Record<string,unknown>>|undefined)?.map(row=><button className="block" type="button" key={String(row.id)} onClick={()=>setProfile(Object.fromEntries(['id',...fields[kind]].filter(key=>row[key]!=null).map(key=>[key,typeof row[key]==='boolean'||typeof row[key]==='number'?row[key] as boolean|number:String(row[key])]))) }>{String(row.title??row.displayName??row.sourceScale)} · {isRtl?'تعديل':'Edit'}</button>)}
      <form className="grid gap-3 py-3" onSubmit={event=>{event.preventDefault();void command('profile',{kind,payload:profile,evidenceReference});}}>{fields[kind].map(field=><label key={field}>{isRtl?labels[field]:field.replace(/([A-Z])/g,' $1')}{field==='versionId'?<select value={String(profile[field]??'')} onChange={e=>setProfile(p=>({...p,versionId:e.target.value}))}><option value="">{isRtl?'النسخة الحالية':'Current profile'}</option>{versions.filter(v=>!['PUBLISHED','SUPERSEDED','ARCHIVED'].includes(v.status)).map(v=><option key={v.id} value={v.id}>{v.sourceFileName??v.versionNumber}</option>)}</select>:<input className="block w-full rounded border p-2" type={field==='isMandatory'?'checkbox':field==='confidence'?'number':'text'} step={field==='confidence'?'0.01':undefined} checked={field==='isMandatory'?profile[field]===true:undefined} value={field==='isMandatory'?undefined:String(profile[field]??'')} onChange={e=>setProfile(p=>({...p,[field]:field==='isMandatory'?e.target.checked:field==='confidence'?Number(e.target.value):e.target.value}))}/>}</label>)}<button disabled={busy} type="submit">{isRtl?'حفظ مع الدليل':'Save with evidence'}</button><button type="button" onClick={()=>setProfile({})}>{isRtl?'سجل جديد':'New record'}</button></form></details>
    <details><summary>{isRtl?'أسماء اختبار أُنشئ يدويًا':'Names for a manually authored test'}</summary><label>العربية<input value={nameAr} onChange={e=>setNameAr(e.target.value)}/></label><label>English<input value={nameEn} onChange={e=>setNameEn(e.target.value)}/></label><button type="button" disabled={busy} onClick={()=>void command('manual-names',{localizedNameAr:nameAr,localizedNameEn:nameEn})}>{isRtl?'اعتماد الأسماء':'Approve names'}</button></details>
    <button type="button" onClick={()=>void adminApiClient.request<any>(`/admin/international-tests/${testId}/usage?page=1`).then(setUsage).catch(err=>setError(err.message))}>{isRtl?'عرض البرامج المتأثرة بتغيير الدرجات':'View programs affected by score changes'}</button>
    {usage&&<div><p>{usage.total} {isRtl?'شرط قبول مرتبط؛ راجع أثر تغيير المقياس قبل نشره.':'linked admission requirements; review scale changes before publishing.'}</p>{usage.data.map((row:any)=><p key={row.id}><Link to={`/universities/${row.universityId}`}>{row.name} · {row.programName}</Link> · {row.minimumScore??'—'} · {row.status}</p>)}<button type="button" disabled={usagePage<=1} onClick={()=>setUsagePage(p=>p-1)}>←</button><span>{usagePage}</span><button type="button" disabled={usagePage*25>=usage.total} onClick={()=>setUsagePage(p=>p+1)}>→</button></div>}
    <button type="button" onClick={()=>void loadTimeline()}>{isRtl?'عرض سجل القرارات':'View decision timeline'}</button>
    {timeline?.data.map((row:any,index:number)=><p key={`${row.timestamp}-${index}`}>{row.timestamp} · {row.action} · {row.actorId} · {row.reason} · {row.correlationId}</p>)}{timeline?.hasMore&&<button type="button" onClick={()=>void loadTimeline(cursor)}>{isRtl?'التالي':'Next'}</button>}
    {history?.releases?.map((row:any)=><p key={row.id}>{isRtl?'نسخة منشورة':'Published release'}: {row.id} · {row.reviewerId} · {row.publishedAt}</p>)}
    {history?.evidence?.map((row:any)=><details key={row.id}><summary>{row.capturedAt} · {row.actorId}</summary><p>{row.payload.sourceUrl} · {row.payload.contentHash}</p></details>)}
  </section>;
}
