import {describe,expect,it,vi} from 'vitest';
import {CourseProgressUseCases} from '../../src/courses/use-cases/CourseProgressUseCases';
import {PrismaCourseCurriculumRepository} from '../../../infrastructure/src/courses/PrismaCourseCurriculumRepository';
import {PrismaCourseProgressRepository} from '../../../infrastructure/src/courses/PrismaCourseProgressRepository';
import {AtomicDomainMutationCoordinator} from '../../src/event-foundation/use-cases/AtomicDomainMutationCoordinator';
import {AtomicAuditedOutboxMutationExecutor} from '../../src/event-foundation/use-cases/AtomicAuditedOutboxMutationExecutor';
const enrolledAt=new Date('2026-10-01T00:00:00.000Z');
function harness(){
 const original:any={id:'c',version:3,status:'PUBLISHED',originType:'NATIVE_MANARATAK_COURSE',certificateAvailable:false,optionalFields:{completionCriteria:{assessmentRequired:true}}};
 const latest:any={...original,version:7,certificateAvailable:true,optionalFields:{completionCriteria:{assessmentRequired:false}}};
 const enrollment:any={id:'e',courseId:'c',studentReferenceId:'s',status:'ACTIVE',progressPercentage:100,enrolledAt,metadata:{courseVersion:3}};
 const curriculum:any={modules:[{id:'m',courseId:'c',title:'Original module',position:1,status:'PUBLISHED'}],lessons:[{id:'l',courseId:'c',moduleId:'m',title:'Original lesson',lessonType:'ARTICLE',position:1,status:'PUBLISHED'}],
  assets:[{id:'asset-ref',lessonId:'l',assetId:'private-handle',assetType:'FILE',position:1,isRequired:true}],quizzes:[{id:'q',courseId:'c',moduleId:'m',title:'Original quiz',passingScore:70,maxAttempts:1,position:1,status:'PUBLISHED'}],
  questions:[{id:'question',courseId:'c',quizId:'q',questionType:'TRUE_FALSE',prompt:'Original question',correctAnswer:true,points:1,position:1,status:'PUBLISHED'}],questionBanks:[]};
 const versions:any={getLearningVersion:vi.fn(async()=>({course:original,curriculum})),getCurriculumSnapshot:vi.fn(async()=>{throw new Error('LATEST_CURRICULUM_MUST_NOT_BE_READ');})};
 let completion:any=null;let attempt:any={id:'a',courseId:'c',quizId:'q',studentReferenceId:'s',status:'IN_PROGRESS',passed:false};let audits=0,events=0;
 const progress:any={withTransaction:()=>progress,findEnrollment:async()=>enrollment,lockEnrollment:vi.fn(),findCompletion:vi.fn(async()=>completion),
  getStudentProgressSnapshot:async()=>({enrollment,lessons:[],quizAttempts:[attempt],completion}),listLessonProgress:async()=>[{lessonId:'l',status:'COMPLETED',progressPercentage:100}],
  findQuizAttempt:async()=>attempt,listQuizAttempts:async()=>[attempt],countQuizAttempts:async()=>1,createQuizAttempt:vi.fn(),submitQuizAttempt:vi.fn(async(data:any)=>{attempt={...attempt,...data,status:data.passed?'PASSED':'FAILED'};return attempt;}),
  upsertLessonProgress:vi.fn(),updateEnrollmentProgress:vi.fn(async()=>enrollment),completeCourse:vi.fn(async(data:any)=>{completion=data;return data;}),markEnrollmentCompleted:vi.fn(),
  enrollWithCapacity:vi.fn(async(data:any)=>({...enrollment,metadata:data.metadata}))};
 const atomic=new AtomicDomainMutationCoordinator(new AtomicAuditedOutboxMutationExecutor({execute:async(fn:any)=>fn({boundaryId:'tx',transactionClient:{}})} as any,{saveInTransaction:async()=>{audits++;}} as any,{appendInTransaction:async()=>{events++;}} as any));
 const uc=new CourseProgressUseCases({findById:async()=>latest} as any,versions,progress,undefined,undefined,atomic);
 return{uc,original,latest,enrollment,curriculum,versions,progress,pass:()=>{attempt.passed=true;},counts:()=>({audits,events})};
}
describe('P13 enrollment-pinned learning definition',()=>{
 it('reads the registered version and never loads latest curriculum into the learner workspace',async()=>{const h=harness();const result=await h.uc.getLearningWorkspace('c','s');expect(h.versions.getLearningVersion).toHaveBeenCalledWith('c',3,enrolledAt);expect(result.curriculum.lessons[0].title).toBe('Original lesson');expect(result.curriculum.questions[0]).not.toHaveProperty('correctAnswer');expect(h.versions.getCurriculumSnapshot).not.toHaveBeenCalled();});
 it('resolves historical asset references from the enrolled definition',async()=>{const h=harness();expect(await h.uc.resolveLearningAsset('c','l','asset-ref','s')).toBe('private-handle');expect(h.versions.getCurriculumSnapshot).not.toHaveBeenCalled();});
 it('rejects a new-version lesson outside the enrolled curriculum',async()=>{const h=harness();await expect(h.uc.markLessonProgress({courseId:'c',studentReferenceId:'s',lessonId:'new-lesson',status:'COMPLETED',progressPercentage:100} as any)).rejects.toThrow('SCOPE_MISMATCH');expect(h.progress.upsertLessonProgress).not.toHaveBeenCalled();});
 it('tracks original lessons against original totals',async()=>{const h=harness();await h.uc.markLessonProgress({courseId:'c',studentReferenceId:'s',lessonId:'l',status:'COMPLETED',progressPercentage:100} as any);expect(h.progress.updateEnrollmentProgress).toHaveBeenCalledWith('c','s',100);});
 it('grades against original answer keys after later course changes',async()=>{const h=harness();const result=await h.uc.submitQuizAttempt({attemptId:'a',courseId:'c',studentReferenceId:'s',answers:{question:true}});expect(result).toMatchObject({score:100,passed:true});expect(h.versions.getCurriculumSnapshot).not.toHaveBeenCalled();});
 it('keeps original required assessments even when the latest version removes that requirement',async()=>{const h=harness();await expect(h.uc.completeCourse('c','s')).rejects.toThrow('COURSE_ASSESSMENT_NOT_PASSED:q');expect(h.progress.completeCourse).not.toHaveBeenCalled();});
 it('records original completion version and certificate eligibility',async()=>{const h=harness();h.pass();await h.uc.completeCourse('c','s');expect(h.progress.completeCourse.mock.calls[0][0]).toMatchObject({courseVersion:3,eligibleForCertificate:false,status:'COMPLETED'});expect(h.progress.lockEnrollment).toHaveBeenCalledWith('c','s');expect(h.counts()).toEqual({audits:1,events:1});});
 it('does not append another completion event if a concurrent request already completed under the enrollment lock',async()=>{const h=harness();h.pass();h.progress.findCompletion.mockResolvedValueOnce(null).mockResolvedValueOnce({id:'existing'});await h.uc.completeCourse('c','s');expect(h.progress.completeCourse).not.toHaveBeenCalled();expect(h.counts()).toEqual({audits:0,events:0});});
 it('fails closed when pinned history is missing rather than falling back to current content',async()=>{const h=harness();h.versions.getLearningVersion.mockResolvedValue(null);await expect(h.uc.getLearningWorkspace('c','s')).rejects.toThrow('ENROLLMENT_VERSION_NOT_FOUND');expect(h.versions.getCurriculumSnapshot).not.toHaveBeenCalled();});
 it('rejects invalid stored version pins',async()=>{const h=harness();h.enrollment.metadata.courseVersion=0;await expect(h.uc.getLearningWorkspace('c','s')).rejects.toThrow('ENROLLMENT_VERSION_INVALID');expect(h.versions.getLearningVersion).not.toHaveBeenCalled();});
 it('records current version during new registration',async()=>{const h=harness();h.progress.findEnrollment=async()=>null;await h.uc.enroll('c','s');expect(h.progress.enrollWithCapacity).toHaveBeenCalledWith({courseId:'c',studentReferenceId:'s',metadata:{courseVersion:7}},null,false);});
});
describe('P13 historical persistence boundaries',()=>{
 function snapshot(){const date=enrolledAt.toISOString();return{course:{id:'c',version:3,status:'PUBLISHED',createdAt:date,updatedAt:date},modules:[],lessons:[],assets:[],quizzes:[],questionBanks:[],questions:[]};}
 it('resolves a legacy enrollment using only published history at or before its enrollment time',async()=>{const findFirst=vi.fn(async()=>({versionNumber:3,snapshot:snapshot()}));const repo=new PrismaCourseCurriculumRepository({courseVersion:{findFirst}} as any);expect((await repo.getLearningVersion('c',undefined,enrolledAt))?.course.version).toBe(3);expect(findFirst.mock.calls[0][0]).toMatchObject({where:{courseId:'c',createdAt:{lte:enrolledAt},snapshot:{path:['course','status'],equals:'PUBLISHED'}}});});
 it('reads an exact pinned version rather than the newest historical row',async()=>{const findUnique=vi.fn(async()=>({versionNumber:3,snapshot:snapshot()}));const repo=new PrismaCourseCurriculumRepository({courseVersion:{findUnique}} as any);await repo.getLearningVersion('c',3,enrolledAt);expect(findUnique).toHaveBeenCalledWith({where:{courseId_versionNumber:{courseId:'c',versionNumber:3}}});});
 it('rejects a foreign or unpublished history snapshot',async()=>{const data=snapshot();data.course.id='foreign';const repo=new PrismaCourseCurriculumRepository({courseVersion:{findUnique:async()=>({versionNumber:3,snapshot:data})}} as any);await expect(repo.getLearningVersion('c',3,enrolledAt)).rejects.toThrow('LEARNING_VERSION_INVALID');});
 it('retires a module and its children without deleting historical IDs or starting a nested transaction',async()=>{const tx:any={courseModule:{update:vi.fn()},courseLesson:{updateMany:vi.fn()},courseQuiz:{updateMany:vi.fn()}};const repo=new PrismaCourseCurriculumRepository({} as any).withTransaction({boundaryId:'tx',transactionClient:tx} as any);await repo.deleteModule('m');expect(tx.courseModule.update).toHaveBeenCalledWith({where:{id:'m'},data:{status:'ARCHIVED'}});expect(tx.courseLesson.updateMany).toHaveBeenCalled();expect(tx.courseQuiz.updateMany).toHaveBeenCalled();});
 it('blocks registration after the course changes version inside the owner lock',async()=>{const create=vi.fn();const tx:any={$queryRaw:vi.fn(async()=>[]),course:{findUnique:async()=>({version:8,status:'PUBLISHED'})},courseEnrollment:{findUnique:async()=>null,create}};const repo=new PrismaCourseProgressRepository({} as any).withTransaction({boundaryId:'tx',transactionClient:tx} as any);await expect(repo.enrollWithCapacity({courseId:'c',studentReferenceId:'s',metadata:{courseVersion:7}},null,false)).rejects.toThrow('ENROLLMENT_VERSION_CHANGED');expect(create).not.toHaveBeenCalled();});
 it('enforces the enrolled quiz attempt cap even if the current archived quiz has a different cap',async()=>{const history=snapshot();(history as any).quizzes=[{id:'q',maxAttempts:1,status:'PUBLISHED'}];const create=vi.fn();const tx:any={$queryRaw:vi.fn(async()=>[]),courseEnrollment:{findUnique:async()=>({status:'ACTIVE',metadata:{courseVersion:3},enrolledAt})},courseVersion:{findUnique:async()=>({versionNumber:3,snapshot:history})},courseQuizAttempt:{findFirst:async()=>null,count:async()=>1,create}};const repo=new PrismaCourseProgressRepository({} as any).withTransaction({boundaryId:'tx',transactionClient:tx} as any);await expect(repo.createQuizAttempt({courseId:'c',quizId:'q',studentReferenceId:'s',attemptNumber:2})).rejects.toThrow('MAX_ATTEMPTS_REACHED');expect(create).not.toHaveBeenCalled();});
});
