import {describe,it,expect,vi} from 'vitest';
import {CertificateUseCases} from '../../src/certificates/use-cases/CertificateUseCases';
import {PrismaCertificateRepository} from '../../../infrastructure/src/certificates/PrismaCertificateRepository';
describe('P14 follow-up asset and template governance',()=>{
 it('accepts an active PDF artifact with its correct MIME',async()=>{const repo:any={findById:async()=>({id:'c'}),attachArtifacts:vi.fn(async data=>data)};const assets:any={findById:async()=>({state:'ACTIVE',classification:'INTERNAL',owner:{ownerType:'Certificate',ownerId:'c'},metadata:{mimeType:'application/pdf'}})};const uc=new CertificateUseCases(repo,{} as any,assets);await uc.attachRenderedArtifacts('c',{certificatePdfAssetId:'pdf-asset'});expect(repo.attachArtifacts).toHaveBeenCalled();});
 it('rejects a purported PDF artifact with image MIME',async()=>{const repo:any={findById:async()=>({id:'c'}),attachArtifacts:vi.fn()};const assets:any={findById:async()=>({state:'ACTIVE',classification:'PUBLIC',metadata:{mimeType:'image/png'}})};await expect(new CertificateUseCases(repo,{} as any,assets).attachRenderedArtifacts('c',{certificatePdfAssetId:'pdf-asset'})).rejects.toThrow('MIME_NOT_ALLOWED');expect(repo.attachArtifacts).not.toHaveBeenCalled();});
 it('does not report issuance ready when only an unrelated issuer is active',async()=>{const repo:any={listTemplates:async()=>[{status:'ACTIVE',issuerId:'suspended',currentVersion:{status:'ACTIVE',issuerId:'suspended'}}],listIssuers:async()=>[{id:'other',status:'ACTIVE'}]};expect((await new CertificateUseCases(repo,{} as any).readiness()).trustedCompletionIssuanceReady).toBe(false);});
 it('rejects a stale template version while holding the owner lock',async()=>{const tx:any={$queryRaw:vi.fn(async()=>[]),certificateTemplate:{findUnique:async()=>({id:'t',status:'DRAFT',currentVersionId:'new'}),update:vi.fn()}};const repo=new PrismaCertificateRepository({$transaction:async(fn:any)=>fn(tx)} as any);await expect(repo.updateTemplate('t',{}, {actorId:'reviewer',expectedTemplateVersionId:'old',expectedTemplateStatus:'DRAFT' as any})).rejects.toThrow('TEMPLATE_STALE');expect(tx.certificateTemplate.update).not.toHaveBeenCalled();});
 it('rejects a stale template state while holding the owner lock',async()=>{const tx:any={$queryRaw:vi.fn(async()=>[]),certificateTemplate:{findUnique:async()=>({id:'t',status:'ACTIVE',currentVersionId:'tv'})}};const repo=new PrismaCertificateRepository({$transaction:async(fn:any)=>fn(tx)} as any);await expect(repo.transitionTemplate('t','APPROVED' as any,{actorId:'reviewer',expectedTemplateVersionId:'tv',expectedTemplateStatus:'PENDING_APPROVAL' as any})).rejects.toThrow('TEMPLATE_STALE');});
});
