import { describe,it,expect,vi,afterEach } from 'vitest';
import { PrismaInternationalTestRepository } from '../../src/international-tests/PrismaInternationalTestRepository';
import { InternationalTestGovernancePersistence,internationalTestCandidateHash } from '../../src/international-tests/InternationalTestGovernancePersistence';
import { InternationalTestPublicationReadinessPolicy } from '@manaratak/domain';
afterEach(()=>vi.restoreAllMocks());
describe('P9 durable release boundary',()=>{
 it.each([['Variant','upsertVariant',{variantName:'v'}],['Section','upsertSection',{sectionName:'s'}],['FeeMetadata','upsertFeeMetadata',{amount:10}],['OfficialLink','upsertOfficialLink',{url:'https://official.test'}],['PreparationMaterial','upsertPreparationMaterial',{title:'Guide'}]])('cannot update another parent’s %s',async(model,method,data)=>{const update=vi.fn(async(args)=>{if(args.where.testId!=='B')throw new Error('OWNER_NOT_FOUND');return {};});const db:any={['internationalTest'+model]:{update}};const repo:any=new PrismaInternationalTestRepository(db,true);await expect(repo[method]('A',{...data,id:'child-B'})).rejects.toThrow('OWNER_NOT_FOUND');expect(update.mock.calls[0][0].where).toEqual({id:'child-B',testId:'A'});});
 it('refuses mutation outside an owner transaction',async()=>{await expect(new InternationalTestGovernancePersistence({} as any,false).advance('test',0)).rejects.toThrow('TRANSACTION_REQUIRED');});
 it('rejects stale CAS and keeps revisions parameterized',async()=>{const db:any={$executeRaw:vi.fn().mockResolvedValueOnce(0).mockResolvedValueOnce(0)};await expect(new InternationalTestGovernancePersistence(db,true).advance('test',3)).rejects.toThrow('REVISION_CONFLICT');expect(db.$executeRaw.mock.calls[1][0].values).toContain(3);});
 it('never exposes mutable legacy root without a matching immutable publication',async()=>{const db:any={internationalTest:{findFirst:vi.fn(async()=>({id:'test',currentPublishedVersionId:'foreign-version'}))},$queryRaw:vi.fn(async()=>[])};expect(await new PrismaInternationalTestRepository(db).findPublishedBySlug('exam')).toBeNull();expect(db.$queryRaw.mock.calls[0][0].text).toContain('v."testId"=s."testId"');expect(db.$queryRaw.mock.calls[0][0].values).toContain('test');});
 it('makes public page and count use the same immutable snapshot source',async()=>{const db:any={$queryRaw:vi.fn().mockResolvedValueOnce([{payload:{id:'test',canonicalName:'Frozen'}}]).mockResolvedValueOnce([{total:1n}])};const result=await new PrismaInternationalTestRepository(db).listPublished({page:2,pageSize:500,searchQuery:"x' OR 1=1"});expect(result.limit).toBe(50);expect(result.data[0].canonicalName).toBe('Frozen');for(const [sql] of db.$queryRaw.mock.calls){expect(sql.text).toContain('InternationalTestPublicationSnapshot');expect(sql.text).not.toContain("x' OR 1=1");}expect(db.$queryRaw.mock.calls[0][0].text).toContain('ORDER BY');});
 it('hashes object key ordering consistently and changes when actual content changes',()=>{expect(internationalTestCandidateHash({a:1,b:2})).toBe(internationalTestCandidateHash({b:2,a:1}));expect(internationalTestCandidateHash({a:1})).not.toBe(internationalTestCandidateHash({a:2}));});
 it('binds source verification, approval and release to the same content and retains two releases',async()=>{
  vi.spyOn(InternationalTestPublicationReadinessPolicy.prototype,'evaluate').mockReturnValue({blockingIssues:[],warnings:[]});
  const state:any={approval:null,verification:null,revision:0};const snapshots:any[]=[];let version=0;
  const evidence={contentHash:'a'.repeat(64),sourceUrl:'https://official.test/source',retrievedAt:new Date(),sourceTrustLevel:'HIGH'};
  const db:any={internationalTestEvidence:{findUnique:async()=>evidence},internationalTestProvider:{findUnique:async()=>({officialWebsite:'https://official.test'})},internationalTestVersion:{findMany:async()=>[],findFirst:async()=>({versionNumber:version}),create:async(input:any)=>{version=input.data.versionNumber;return input.data;}},$queryRaw:vi.fn(async(sql:any)=>sql.text.includes('SELECT "approval"')?[state]:[]),$executeRaw:vi.fn(async(sql:any)=>{if(sql.text.includes('SET "verification"'))state.verification=JSON.parse(sql.values[0]);else if(sql.text.includes('SET "approval"'))state.approval=JSON.parse(sql.values[0]);else if(sql.text.includes('INSERT INTO "InternationalTestPublicationSnapshot"'))snapshots.push(JSON.parse(sql.values[3]));return 1;})};
  const helper=new InternationalTestGovernancePersistence(db,true);const test:any={id:'test',canonicalName:'First',providerId:'provider',testCategory:'OTHER',isSourceVerified:true,localizedNameAr:'اختبار',localizedNameEn:'Test',officialLinks:[]};
  await helper.execute(test,'VERIFY',{reason:'Source reviewed'},'reviewer');await helper.execute(test,'APPROVE',{reason:'Candidate reviewed'},'reviewer');await helper.execute(test,'PUBLISH',{reason:'Release approved'},'publisher');
  test.canonicalName='Second';await expect(helper.execute(test,'PUBLISH',{reason:'Release approved'},'publisher')).rejects.toThrow('APPROVAL_STALE');expect(snapshots[0].canonicalName).toBe('First');await helper.execute(test,'APPROVE',{reason:'Second candidate reviewed'},'reviewer');await helper.execute(test,'PUBLISH',{reason:'Release approved'},'publisher');expect(snapshots.map(s=>s.canonicalName)).toEqual(['First','Second']);expect(snapshots[0].currentPublishedVersionId).not.toBe(snapshots[1].currentPublishedVersionId);
 });
});
