export const ADMIN_PERMISSION_CATALOG = [
  {
    key: 'admin:credentials:manage',
    domain: 'credentials',
    action: 'manage',
    labelAr: 'إدارة — بيانات الاعتماد',
    labelEn: 'Manage — Credentials',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'CRITICAL',
    delegable: false,
  },
  {
    key: 'admin:identities:manage',
    domain: 'identities',
    action: 'manage',
    labelAr: 'إدارة — الهويات',
    labelEn: 'Manage — Identities',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'CRITICAL',
    delegable: false,
  },
  {
    key: 'admin:authorization:manage',
    domain: 'authorization',
    action: 'manage',
    labelAr: 'إدارة — الصلاحيات والأدوار',
    labelEn: 'Manage — Authorization',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'CRITICAL',
    delegable: false,
  },
  {
    key: 'admin:audit:manage',
    domain: 'audit',
    action: 'manage',
    labelAr: 'إدارة — سجل التدقيق',
    labelEn: 'Manage — Audit',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
  {
    key: 'admin:assets:reuse',
    domain: 'assets',
    action: 'reuse',
    labelAr: 'اختيار ومعاينة — الأصول القابلة لإعادة الاستخدام',
    labelEn: 'Select and preview — Reusable assets',
    descriptionAr: 'البحث عن الأصول النشطة العامة أو الداخلية واختيارها ومعاينتها دون صلاحيات إدارة دورة الحياة أو الحذف.',
    descriptionEn: 'Search, select, and preview reusable active public/internal assets without lifecycle or deletion authority.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:assets:manage',
    domain: 'assets',
    action: 'manage',
    labelAr: 'إدارة — الأصول',
    labelEn: 'Manage — Assets',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
  {
    key: 'admin:imports:manage',
    domain: 'imports',
    action: 'manage',
    labelAr: 'إدارة — الاستيراد',
    labelEn: 'Manage — Imports',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:reference-data:manage',
    domain: 'reference-data',
    action: 'manage',
    labelAr: 'إدارة — البيانات المرجعية',
    labelEn: 'Manage — Reference data',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:academic-taxonomy:manage',
    domain: 'academic-taxonomy',
    action: 'manage',
    labelAr: 'إدارة — التصنيف الأكاديمي',
    labelEn: 'Manage — Academic taxonomy',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:international-tests:manage',
    domain: 'international-tests',
    action: 'manage',
    labelAr: 'إدارة — الاختبارات الدولية',
    labelEn: 'Manage — International tests',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:universities:manage',
    domain: 'universities',
    action: 'manage',
    labelAr: 'إدارة — الجامعات',
    labelEn: 'Manage — Universities',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:majors:manage',
    domain: 'majors',
    action: 'manage',
    labelAr: 'إدارة — التخصصات',
    labelEn: 'Manage — Majors',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:scholarships:manage',
    domain: 'scholarships',
    action: 'manage',
    labelAr: 'إدارة — المنح',
    labelEn: 'Manage — Scholarships',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:courses:manage',
    domain: 'courses',
    action: 'manage',
    labelAr: 'إدارة — الدورات',
    labelEn: 'Manage — Courses',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:certificates:view',
    domain: 'certificates',
    action: 'view',
    labelAr: 'قراءة — الشهادات',
    labelEn: 'View — Certificates',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:certificates:templates:author',
    domain: 'certificates',
    action: 'author',
    labelAr: 'تحرير — الشهادات',
    labelEn: 'Author — Certificates',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:certificates:templates:approve',
    domain: 'certificates',
    action: 'approve',
    labelAr: 'اعتماد — الشهادات',
    labelEn: 'Approve — Certificates',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
  {
    key: 'admin:certificates:lifecycle:manage',
    domain: 'certificates',
    action: 'manage',
    labelAr: 'إدارة — الشهادات',
    labelEn: 'Manage — Certificates',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:certificates:issuers:manage',
    domain: 'certificates',
    action: 'manage',
    labelAr: 'إدارة — الشهادات',
    labelEn: 'Manage — Certificates',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:students:support',
    domain: 'students',
    action: 'support',
    labelAr: 'قراءة دعم — دعم الطلاب',
    labelEn: 'Support read — Student support',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:students:support:mutate',
    domain: 'students',
    action: 'mutate',
    labelAr: 'تعديل الدعم — دعم الطلاب',
    labelEn: 'Support mutation — Student support',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
  {
    key: 'admin:student-tools:manage',
    domain: 'student-tools',
    action: 'manage',
    labelAr: 'إدارة — أدوات الطلاب',
    labelEn: 'Manage — Student tools',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:cms:manage',
    domain: 'cms',
    action: 'manage',
    labelAr: 'إدارة — إدارة المحتوى',
    labelEn: 'Manage — Content management',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:services:manage',
    domain: 'services',
    action: 'manage',
    labelAr: 'إدارة — الخدمات',
    labelEn: 'Manage — Services',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:finance:manage',
    domain: 'finance',
    action: 'manage',
    labelAr: 'إدارة — المالية',
    labelEn: 'Manage — Finance',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
  {
    key: 'admin:careers:manage',
    domain: 'careers',
    action: 'manage',
    labelAr: 'إدارة — الوظائف',
    labelEn: 'Manage — Careers',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:ai:manage',
    domain: 'ai',
    action: 'manage',
    labelAr: 'إدارة — الذكاء الاصطناعي',
    labelEn: 'Manage — AI platform',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
  {
    key: 'admin:settings:manage',
    domain: 'settings',
    action: 'manage',
    labelAr: 'إدارة — الإعدادات',
    labelEn: 'Manage — Settings',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
  {
    key: 'admin:platform:manage',
    domain: 'platform',
    action: 'manage',
    labelAr: 'إدارة — تشغيل المنصة',
    labelEn: 'Manage — Platform operations',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
] as const;

export const KNOWN_ADMIN_PERMISSIONS = ADMIN_PERMISSION_CATALOG.map((entry) => entry.key);
