export const ADMIN_PERMISSION_CATALOG = [
  {
    key: 'admin:credentials:manage',
    domain: 'credentials',
    action: 'manage',
    labelAr: 'إدارة — بيانات الاعتماد',
    labelEn: 'Manage — Credentials',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'CRITICAL',
    delegable: false,
  },
  {
    key: 'admin:identities:manage',
    domain: 'identities',
    action: 'manage',
    labelAr: 'إدارة — الهويات',
    labelEn: 'Manage — Identities',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'CRITICAL',
    delegable: false,
  },
  {
    key: 'admin:authorization:manage',
    domain: 'authorization',
    action: 'manage',
    labelAr: 'إدارة — الصلاحيات والأدوار',
    labelEn: 'Manage — Authorization',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'CRITICAL',
    delegable: false,
  },
  {
    key: 'admin:audit:manage',
    domain: 'audit',
    action: 'manage',
    labelAr: 'إدارة — سجل التدقيق',
    labelEn: 'Manage — Audit',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
  {
    key: 'admin:assets:reuse',
    domain: 'assets',
    action: 'reuse',
    labelAr: 'اختيار ومعاينة — الأصول القابلة لإعادة الاستخدام',
    labelEn: 'Select and preview — Reusable assets',
    descriptionAr: 'البحث عن الأصول النشطة العامة أو الداخلية واختيارها ومعاينتها دون صلاحيات إدارة دورة الحياة أو الحذف.',
    descriptionEn: 'Search, select, and preview reusable active public/internal assets without lifecycle or deletion authority.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:assets:manage',
    domain: 'assets',
    action: 'manage',
    labelAr: 'إدارة — الأصول',
    labelEn: 'Manage — Assets',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
  {
    key: 'admin:imports:manage',
    domain: 'imports',
    action: 'manage',
    labelAr: 'إدارة — الاستيراد',
    labelEn: 'Manage — Imports',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:reference-data:manage',
    domain: 'reference-data',
    action: 'manage',
    labelAr: 'إدارة — البيانات المرجعية',
    labelEn: 'Manage — Reference data',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:academic-taxonomy:manage',
    domain: 'academic-taxonomy',
    action: 'manage',
    labelAr: 'إدارة — التصنيف الأكاديمي',
    labelEn: 'Manage — Academic taxonomy',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {key:'admin:majors:review',domain:'majors',action:'review',labelAr:'مراجعة التخصصات',labelEn:'Review majors',descriptionAr:'اعتماد نسخ التخصصات والمراجع الجديدة.',descriptionEn:'Review major versions and discovery references.',risk:'STANDARD',delegable:true},
  {key:'admin:majors:publish',domain:'majors',action:'publish',labelAr:'نشر التخصصات',labelEn:'Publish majors',descriptionAr:'نشر النسخ المعتمدة وإلغاء نشرها.',descriptionEn:'Publish and unpublish approved major versions.',risk:'STANDARD',delegable:true},
  {key:'admin:international-tests:review',domain:'international-tests',action:'review',labelAr:'مراجعة الاختبارات الدولية',labelEn:'Review international tests',descriptionAr:'صلاحية مستقلة؛ تتطلب إدارة الاختبارات للوصول.',descriptionEn:'Separate operation permission; test management is required for access.',risk:'STANDARD',delegable:true},
  {key:'admin:international-tests:verify',domain:'international-tests',action:'verify',labelAr:'التحقق من مصادر الاختبارات',labelEn:'Verify test sources',descriptionAr:'صلاحية مستقلة؛ تتطلب إدارة الاختبارات للوصول.',descriptionEn:'Separate operation permission; test management is required for access.',risk:'STANDARD',delegable:true},
  {key:'admin:international-tests:publish',domain:'international-tests',action:'publish',labelAr:'نشر الاختبارات الدولية',labelEn:'Publish international tests',descriptionAr:'صلاحية مستقلة؛ تتطلب إدارة الاختبارات للوصول.',descriptionEn:'Separate operation permission; test management is required for access.',risk:'STANDARD',delegable:true},
  {
    key: 'admin:international-tests:manage',
    domain: 'international-tests',
    action: 'manage',
    labelAr: 'إدارة — الاختبارات الدولية',
    labelEn: 'Manage — International tests',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:universities:manage',
    domain: 'universities',
    action: 'manage',
    labelAr: 'إدارة — الجامعات',
    labelEn: 'Manage — Universities',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:majors:manage',
    domain: 'majors',
    action: 'manage',
    labelAr: 'إدارة — التخصصات',
    labelEn: 'Manage — Majors',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:scholarships:manage',
    domain: 'scholarships',
    action: 'manage',
    labelAr: 'إدارة — المنح',
    labelEn: 'Manage — Scholarships',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:courses:manage',
    domain: 'courses',
    action: 'manage',
    labelAr: 'إدارة — الدورات',
    labelEn: 'Manage — Courses',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:certificates:view',
    domain: 'certificates',
    action: 'view',
    labelAr: 'قراءة — الشهادات',
    labelEn: 'View — Certificates',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:certificates:templates:author',
    domain: 'certificates',
    action: 'author',
    labelAr: 'تحرير — الشهادات',
    labelEn: 'Author — Certificates',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:certificates:templates:approve',
    domain: 'certificates',
    action: 'approve',
    labelAr: 'اعتماد — الشهادات',
    labelEn: 'Approve — Certificates',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
  {
    key: 'admin:certificates:lifecycle:manage',
    domain: 'certificates',
    action: 'manage',
    labelAr: 'إدارة — الشهادات',
    labelEn: 'Manage — Certificates',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:certificates:issuers:manage',
    domain: 'certificates',
    action: 'manage',
    labelAr: 'إدارة — الشهادات',
    labelEn: 'Manage — Certificates',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:certificates:issuers:approve',
    domain: 'certificates',
    action: 'approve',
    labelAr: 'اعتماد جهات إصدار — الشهادات',
    labelEn: 'Approve issuers — Certificates',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
  {
    key: 'admin:certificates:download',
    domain: 'certificates',
    action: 'download',
    labelAr: 'تنزيل — الشهادات',
    labelEn: 'Download — Certificates',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:certificates:lifecycle:approve',
    domain: 'certificates',
    action: 'approve',
    labelAr: 'اعتماد تصحيح وإعادة تحقق — الشهادات',
    labelEn: 'Approve corrections and revalidation — Certificates',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
  {
    key: 'admin:students:support',
    domain: 'students',
    action: 'support',
    labelAr: 'قراءة دعم — دعم الطلاب',
    labelEn: 'Support read — Student support',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:students:support:mutate',
    domain: 'students',
    action: 'mutate',
    labelAr: 'تعديل الدعم — دعم الطلاب',
    labelEn: 'Support mutation — Student support',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
  {
    key: 'admin:student-tools:manage',
    domain: 'student-tools',
    action: 'manage',
    labelAr: 'إدارة — أدوات الطلاب',
    labelEn: 'Manage — Student tools',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {key:'admin:cms:view',domain:'cms',action:'view',labelAr:'قراءة محتوى الموقع',labelEn:'View site content',descriptionAr:'صلاحية مستقلة ولا تتضمن تفويض الاعتماد أو النشر تلقائيا.',descriptionEn:'Independent capability; does not implicitly grant review or publication.',risk:'STANDARD',delegable:true},
  {key:'admin:cms:author',domain:'cms',action:'author',labelAr:'تحرير محتوى الموقع',labelEn:'Author site content',descriptionAr:'صلاحية مستقلة ولا تتضمن تفويض الاعتماد أو النشر تلقائيا.',descriptionEn:'Independent capability; does not implicitly grant review or publication.',risk:'STANDARD',delegable:true},
  {key:'admin:cms:review',domain:'cms',action:'review',labelAr:'اعتماد المحتوى التحريري',labelEn:'Review editorial content',descriptionAr:'صلاحية مستقلة ولا تتضمن تفويض الاعتماد أو النشر تلقائيا.',descriptionEn:'Independent capability; does not implicitly grant review or publication.',risk:'HIGH',delegable:true},
  {key:'admin:cms:publish',domain:'cms',action:'publish',labelAr:'نشر وأرشفة المحتوى',labelEn:'Publish and archive content',descriptionAr:'صلاحية مستقلة ولا تتضمن تفويض الاعتماد أو النشر تلقائيا.',descriptionEn:'Independent capability; does not implicitly grant review or publication.',risk:'HIGH',delegable:true},
  {key:'admin:cms:redirects:manage',domain:'cms',action:'redirects:manage',labelAr:'إدارة تحويلات الموقع',labelEn:'Manage site redirects',descriptionAr:'صلاحية مستقلة ولا تتضمن تفويض الاعتماد أو النشر تلقائيا.',descriptionEn:'Independent capability; does not implicitly grant review or publication.',risk:'HIGH',delegable:true},
  {key:'admin:cms:navigation:manage',domain:'cms',action:'navigation:manage',labelAr:'إدارة قوائم التنقل',labelEn:'Manage navigation menus',descriptionAr:'صلاحية مستقلة ولا تتضمن تفويض الاعتماد أو النشر تلقائيا.',descriptionEn:'Independent capability; does not implicitly grant review or publication.',risk:'STANDARD',delegable:true},
  {key:'admin:cms:schemas:approve',domain:'cms',action:'approve',labelAr:'اعتماد مخططات CMS',labelEn:'Approve CMS block schemas',descriptionAr:'اعتماد فني مستقل عن مؤلف المخطط.',descriptionEn:'Independent checker approval for immutable schema versions.',risk:'HIGH',delegable:true},
  {key:'admin:cms:schemas:manage',domain:'cms',action:'schemas:manage',labelAr:'إدارة مخططات الكتل',labelEn:'Manage block schemas',descriptionAr:'صلاحية مستقلة ولا تتضمن تفويض الاعتماد أو النشر تلقائيا.',descriptionEn:'Independent capability; does not implicitly grant review or publication.',risk:'HIGH',delegable:true},
  {key:'admin:cms:operations:run',domain:'cms',action:'operations:run',labelAr:'تشغيل مهام النشر المجدولة',labelEn:'Run publishing jobs',descriptionAr:'صلاحية مستقلة ولا تتضمن تفويض الاعتماد أو النشر تلقائيا.',descriptionEn:'Independent capability; does not implicitly grant review or publication.',risk:'CRITICAL',delegable:false},
  {
    key: 'admin:cms:manage',
    domain: 'cms',
    action: 'manage',
    labelAr: 'إدارة — إدارة المحتوى',
    labelEn: 'Manage — Content management',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:services:manage',
    domain: 'services',
    action: 'manage',
    labelAr: 'إدارة — الخدمات',
    labelEn: 'Manage — Services',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:finance:manage',
    domain: 'finance',
    action: 'manage',
    labelAr: 'إدارة — المالية',
    labelEn: 'Manage — Finance',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
  {
    key: 'admin:careers:manage',
    domain: 'careers',
    action: 'manage',
    labelAr: 'إدارة — الوظائف',
    labelEn: 'Manage — Careers',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'STANDARD',
    delegable: true,
  },
  {
    key: 'admin:ai:manage',
    domain: 'ai',
    action: 'manage',
    labelAr: 'إدارة — الذكاء الاصطناعي',
    labelEn: 'Manage — AI platform',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
  {
    key: 'admin:settings:manage',
    domain: 'settings',
    action: 'manage',
    labelAr: 'إدارة — الإعدادات',
    labelEn: 'Manage — Settings',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
  {
    key: 'admin:platform:manage',
    domain: 'platform',
    action: 'manage',
    labelAr: 'إدارة — تشغيل المنصة',
    labelEn: 'Manage — Platform operations',
    descriptionAr: 'تسمح بهذه العملية ضمن المجال فقط؛ لا تمنح صلاحيات مجالات أخرى.',
    descriptionEn:
      'Allows this operation within its domain; does not grant access to other domains.',
    risk: 'HIGH',
    delegable: true,
  },
] as const;

export const KNOWN_ADMIN_PERMISSIONS = ADMIN_PERMISSION_CATALOG.map((entry) => entry.key);
