/** Certificate workspace copy shared by Admin, Public and Student. */
const english: Readonly<Record<string, string>> = {
  'تحتاج الشهادة إلى إعادة تحقق معتمدة قبل استخدامها.':
    'The certificate requires approved revalidation before use.',
  'تعذر إثبات سلامة الشهادة؛ لم تُعرض بياناتها.':
    'Certificate integrity could not be established; its claims are hidden.',
  'تعديل جهة الإصدار': 'Edit issuer',
  'قالب منارتك الرسمي': 'MANARATAK official template',
  'شهادة إتمام': 'Certificate of Completion',
  'تشهد منصة منارتك بأن المتعلم قد أتم بنجاح متطلبات هذه الدورة واستحق شهادة الإتمام الرقمية القابلة للتحقق.':
    'MANARATAK certifies that this learner completed the course requirements and earned a verifiable digital certificate.',
  'إدارة الشهادات — منارتك': 'MANARATAK Certificates Office',
  'توقيع الإصدار الرقمي': 'Digital issuance signature',
  'MANARATAK — منارتك': 'MANARATAK',
  'تعذر تحميل مركز الشهادات.': 'Could not load the certificate center.',
  'تم إنشاء نسخة جديدة من القالب مع الحفاظ على النسخة التاريخية.':
    'A new template version was created; the historical version was preserved.',
  'تم إنشاء مسودة القالب. يجب أن تمر بالمراجعة والاعتماد قبل التفعيل.':
    'Template draft created. Review and approval are required before activation.',
  'تعذر حفظ القالب.': 'Could not save the template.',
  'تعذر تغيير حالة القالب.': 'Could not change template status.',
  'أنشئ جهة إصدار نشطة أولًا.': 'Create an active issuer first.',
  'تم إنشاء مسودة قالب منارتك الرسمي.': 'MANARATAK official template draft created.',
  'تعذر إنشاء القالب الافتراضي.': 'Could not create the default template.',
  'تم حفظ جهة الإصدار؛ الاعتماد يحتاج مراجعًا مستقلًا.':
    'Issuer saved; independent approval is required.',
  'تعذر إنشاء جهة الإصدار.': 'Could not create the issuer.',
  'مركز شهادات منارتك': 'MANARATAK Certificate Center',
  'الإصدار، القوالب، التحقق والحوكمة': 'Issuance, templates, verification and governance',
  'الإصدار الأولي لا يتم يدويًا من هذه الصفحة. الشهادة تُنشأ فقط بعد حدث إكمال موثوق من نظام الدورات، ثم يمتلك هذا القسم دورة حياتها والتحقق العام منها.':
    'Initial certificates are issued only after trusted learning completion. This workspace manages their lifecycle and verification.',
  'تحديث مركز الشهادات': 'Refresh certificate center',
  تحديث: 'Refresh',
  الإجمالي: 'Total',
  نشطة: 'Active',
  ملغاة: 'Revoked',
  مؤرشفة: 'Archived',
  'تنتهي قريبًا': 'Expiring soon',
  القوالب: 'Templates',
  'عمليات تحقق': 'Verifications',
  'سجل الشهادات': 'Certificate registry',
  'جهات الإصدار': 'Issuers',
  'الجاهزية والحوكمة': 'Readiness and governance',
  'السجل الرسمي': 'Official registry',
  'لا يوجد حذف نهائي للشهادات الصادرة؛ التصحيح يتم بالإلغاء ثم إعادة الإصدار.':
    'Issued certificates cannot be deleted. Corrections require revocation and reissue.',
  'رقم الشهادة، الاسم، الدورة...': 'Certificate number, name, course...',
  'كل الحالات': 'All statuses',
  'جهة الإصدار': 'Issuer',
  الكل: 'All',
  'مرجع الطالب': 'Student reference',
  'نسخة القالب': 'Template version',
  من: 'From',
  'من تاريخ': 'From date',
  إلى: 'To',
  'إلى تاريخ': 'To date',
  الشهادة: 'Certificate',
  المستفيد: 'Recipient',
  الإنجاز: 'Achievement',
  الحالة: 'Status',
  الإصدار: 'Issued',
  إجراء: 'Action',
  'اسم غير متاح — راجع Identity snapshot': 'Name unavailable; check the Identity snapshot',
  فتح: 'Open',
  'لا توجد شهادات مطابقة.': 'No matching certificates.',
  'صفحات الشهادات': 'Certificate pages',
  السابق: 'Previous',
  صفحة: 'Page',
  '· الإجمالي': '· Total',
  التالي: 'Next',
  'قوالب الشهادات': 'Certificate templates',
  'القالب Versioned وMaker/Checker؛ تعديل قالب لا يغيّر الشهادات التاريخية.':
    'Templates are versioned and independently approved. Editing does not alter historical certificates.',
  'إنشاء القالب الرسمي': 'Create official template',
  'قالب جديد': 'New template',
  'معاينة كبيرة': 'Large preview',
  'نسخة تعديل': 'Edit version',
  'لا يوجد قالب. ابدأ بجهة إصدار ثم أنشئ قالب منارتك الرسمي.':
    'No template. Create an issuer, then the official template.',
  'الجهة والمفتاح والأصل المرئي جزء من سلطة إصدار الشهادة.':
    'Issuer, signing key and visual assets form the certificate authority.',
  'جهة إصدار': 'New issuer',
  النوع: 'Type',
  محمي: 'Protected',
  'جهة الاعتماد الخارجية': 'External accreditation authority',
  'غير مطلوب — شهادة إتمام من المنصة': 'Not required; platform completion certificate',
  'غير محدد': 'Not specified',
  تعديل: 'Edit',
  'تعذر التعليق': 'Could not suspend authority',
  'تعليق سلطة الإصدار': 'Suspend issuance authority',
  'مراجعة الاعتماد': 'Review authority',
  'قواعد الثقة': 'Trust rules',
  '• الإصدار الأولي من حدث CourseCompleted/LearningPathCompleted موثوق فقط.':
    '• Initial issuance accepts only trusted CourseCompleted/LearningPathCompleted events.',
  '• شهادة منارتك هي Certificate of Completion وليست اعتمادًا أكاديميًا أو ترخيصًا مهنيًا.':
    '• MANARATAK certificates prove completion; they do not confer academic accreditation or professional licensing.',
  '• لكل Completion هوية إصدار واحدة؛ replay لن ينشئ نسخة مكررة.':
    '• Each completion has one initial issuance; replay cannot duplicate it.',
  '• QR يفتح صفحة التحقق العامة وليس API JSON.': '• The QR opens the public verification page.',
  '• الاسم والدورة والقالب والجهة وتاريخ الإكمال تدخل في الظرف الموقّع.':
    '• Recipient, achievement, template, issuer and completion date are signed.',
  '• الشهادة الصادرة لا تُحذف؛ إلغاء ثم إعادة إصدار عند التصحيح.':
    '• Issued records are preserved; corrections use revocation and reissue.',
  'جاهزية التشغيل': 'Runtime readiness',
  'قالب Active': 'Active template',
  'جهة إصدار Active': 'Active issuer',
  'رابط تحقق عام': 'Public verification URL',
  'يُقرأ من CERTIFICATE_PUBLIC_VERIFICATION_BASE_URL ولا يُفترض جاهزًا تلقائيًا.':
    'Configured through CERTIFICATE_PUBLIC_VERIFICATION_BASE_URL; readiness requires evidence.',
  'لا تظهر READY في الإنتاج إلا عند وجود موفر توقيع ومرجع مفتاح.':
    'Production readiness requires an opaque signing provider and key reference.',
  'PDF/Preview عبر EAP': 'PDF/Preview through EAP',
  'الإصدار يسجل AWAITING_EAP_RENDER حتى يعيد عامل EAP أصول PDF/Preview/QR.':
    "Issuance awaits the worker's PDF, preview and QR artifacts.",
  'معاينة القالب النشط': 'Active template preview',
  'إنشاء نسخة جديدة من القالب': 'Create a new template version',
  'إنشاء قالب شهادة': 'Create certificate template',
  الكود: 'Code',
  'الاسم الإداري': 'Administrative name',
  'الاسم العربي': 'Arabic name',
  'الاسم الإنجليزي': 'English name',
  'اختر...': 'Select...',
  'لغة الشهادة': 'Certificate language',
  'عربي + English': 'Arabic + English',
  العربية: 'Arabic',
  'اتجاه القالب': 'Template orientation',
  أفقي: 'Landscape',
  عمودي: 'Portrait',
  'العنوان العربي': 'Arabic title',
  'العنوان الإنجليزي': 'English title',
  'النص العربي': 'Arabic body',
  'النص الإنجليزي': 'English body',
  'اسم التوقيع العربي': 'Arabic signatory name',
  'صفة التوقيع': 'Signatory title',
  'اللون الأساسي': 'Primary color',
  الذهبي: 'Gold',
  'أصول القالب - EAP': 'Template assets — EAP',
  'سياسة الصلاحية': 'Validity policy',
  السياسة: 'Policy',
  دائمة: 'Permanent',
  تنتهي: 'Expires',
  'قابلة للتجديد': 'Renewable',
  'مدة الصلاحية بالأيام': 'Validity in days',
  'فترة التجديد بالأيام': 'Renewal interval in days',
  'سياسة التجديد': 'Renewal policy',
  'تتطلب إعادة تحقق دورية': 'Requires periodic revalidation',
  إلغاء: 'Cancel',
  'حفظ كمسودة': 'Save as draft',
  'اعتماد جهة الإصدار': 'Approve issuer',
  'تعذر الاعتماد': 'Could not approve',
  'يجب أن تكون وثيقة التفويض خاصة ومملوكة لهذه الجهة، وأن يكون المراجع مختلفًا عن المنشئ.':
    'Authorization evidence must be private, owned by this issuer, and reviewed by someone other than its creator.',
  'مرجع وثيقة التفويض': 'Authorization evidence reference',
  'مرجع السلطة': 'Authority reference',
  'سبب الاعتماد': 'Approval reason',
  اعتماد: 'Approve',
  'إنشاء جهة إصدار': 'Create issuer',
  الاسم: 'Name',
  'جهة اعتماد خارجية': 'External authority',
  'مرجع الاعتماد الخارجي': 'External accreditation reference',
  'لجهة MANARATAK لا نكتب اعتمادًا خارجيًا ما لم يوجد أساس قانوني حقيقي. الشهادة الافتراضية توصف كشهادة إتمام رقمية من المنصة.':
    'MANARATAK certificates describe platform completion. External accreditation requires independent legal evidence.',
  إنشاء: 'Create',
  'معاينة القالب': 'Template preview',
  '— اختياري': '— optional',
  إغلاق: 'Close',
  'إرسال للمراجعة': 'Submit for review',
  تفعيل: 'Activate',
  'إيقاف تدريجي': 'Deprecate',
  أرشفة: 'Archive',
  'تغيير الحالة': 'Change status',
  'تعذر تحميل الشهادة.': 'Could not load the certificate.',
  'تعذر التنزيل': 'Download failed',
  'تعذر تنفيذ العملية.': 'Could not perform the action.',
  'لم يتم العثور على الشهادة.': 'Certificate not found.',
  'العودة إلى سجل الشهادات': 'Back to certificate registry',
  'نسخ الرمز': 'Copy code',
  'صفحة التحقق': 'Verification page',
  'النسخة التاريخية للقالب غير متاحة للمعاينة، لكن سجل الشهادة محفوظ.':
    'Historical template version is unavailable; the certificate record is preserved.',
  'شهادة نشطة': 'Active certificate',
  'التوقيع مطابق': 'Signature matches',
  'فشل التحقق من التوقيع': 'Signature verification failed',
  'لم يُفحص': 'Not checked',
  'بيانات الشهادة': 'Certificate details',
  'لم يُلتقط الاسم عند الإصدار': 'Name not captured at issuance',
  'الجهة المصدرة': 'Issuer',
  'تاريخ الإكمال': 'Completion date',
  'تاريخ الإصدار': 'Issue date',
  الانتهاء: 'Expiry',
  القالب: 'Template',
  'المهارات والنتيجة': 'Skills and result',
  'لا توجد مهارات مثبتة في Snapshot.': 'No skills recorded in the snapshot.',
  'التقدير:': 'Grade:',
  'دفتر التدقيق': 'Audit ledger',
  'لا توجد أحداث مسجلة.': 'No recorded events.',
  'إلغاء رسمي': 'Revoke',
  'إعادة إصدار': 'Reissue',
  تجديد: 'Renew',
  'تنزيل PDF': 'Download PDF',
  'الحذف النهائي غير متاح تصميميًا. الشهادة التاريخية تبقى قابلة للتدقيق حتى بعد الإلغاء أو الاستبدال.':
    'Historical records remain available for audit after revocation or replacement.',
  تأكيد: 'Confirm',
  'سيتم تسجيل القرار والسبب وهوية المنفذ في دفتر التدقيق.':
    'The action, reason and operator identity will be recorded in the ledger.',
  'الاسم على الشهادة الجديدة': 'Name on replacement certificate',
  'اكتب السبب الرسمي': 'Enter the official reason',
  تراجع: 'Back',
  'إلغاء الشهادة': 'Revoke certificate',
  'إعادة الإصدار': 'Reissue',
  'تجديد الشهادة': 'Renew certificate',
  'أرشفة الشهادة': 'Archive certificate',
  'أدخل رمز التحقق من الشهادة.': 'Enter the certificate verification code.',
  'لم يتم العثور على شهادة بهذا الرمز.': 'No certificate found for this code.',
  'تعذر التحقق من الشهادة.': 'Could not verify the certificate.',
  'منصة التحقق من الشهادات': 'Certificate verification',
  'أدخل الرمز المطبوع على الشهادة أو امسح QR للتأكد من سلامة الختم الرقمي وحالة الشهادة لحظيًا.':
    'Enter the printed code or scan the QR to verify the signature and current status.',
  'رمز التحقق من الشهادة': 'Certificate verification code',
  'جارٍ التحقق...': 'Verifying...',
  'تحقق من الشهادة': 'Verify certificate',
  'الثقة والخصوصية': 'Trust and privacy',
  'يتم فحص الحالة والختم المشفر مباشرة من سجل الشهادات. لا نعرض البريد أو بيانات الاتصال أو أي معلومات طالب خاصة.':
    'Status and signature are checked against the certificate registry. Email and private student contact information are withheld.',
  'أدخل رمز التحقق لعرض نتيجة موثوقة من سجل الشهادات.':
    'Enter a code to obtain a verified registry result.',
  'شهادة صحيحة وموثقة': 'Valid, verified certificate',
  'الشهادة غير صالحة': 'Certificate is invalid',
  'الدورة أو البرنامج': 'Course or program',
  'غير متاح': 'Unavailable',
  'صاحب الشهادة': 'Certificate recipient',
  'مرجع طالب محمي': 'Protected student reference',
  'رقم الشهادة': 'Certificate number',
  'صلاحية الشهادة': 'Certificate validity',
  'محددة المدة': 'Time limited',
  'تاريخ الانتهاء': 'Expiry date',
  'لا يوجد تاريخ انتهاء': 'No expiry date',
  'تعذر إثبات بيانات الشهادة؛ لا تُعرض ادعاءات غير موثوقة.':
    'Certificate claims could not be verified and are withheld.',
  هذه: 'This is a',
  'شهادة إتمام رقمية صادرة من منصة منارتك': 'MANARATAK digital completion certificate',
  'لإثبات إكمال متطلبات التعلم المحددة. لا تمثل درجة جامعية أو اعتمادًا مهنيًا خارجيًا ما لم تظهر جهة اعتماد مستقلة صراحة ضمن بيانات الشهادة.':
    'proving completion of the specified learning requirements. It is not a university degree or external professional accreditation unless a verified independent authority is explicitly stated.',
  'الختم الرقمي سليم': 'Digital signature verified',
  'تعذر إثبات سلامة الختم': 'Signature integrity could not be established',
  'تمت مقارنة البيانات المختومة مع البصمة المشفرة المحفوظة في سجل الشهادات.':
    'Signed data was compared against the stored cryptographic fingerprint.',
  'المهارات المثبتة': 'Verified skills',
  '. لم تعد هذه الشهادة صالحة للتحقق.': '. This certificate is no longer valid.',
  'رابط ملف الشهادة غير صالح.': 'Invalid certificate file URL.',
  'تعذر تنزيل الشهادة.': 'Could not download the certificate.',
  'تعذر تحميل الشهادة': 'Could not load the certificate',
  'QR للتحقق من الشهادة': 'Certificate verification QR',
  'التحقق من الشهادة': 'Verify certificate',
  'جارٍ التحميل…': 'Downloading…',
  'تحميل الشهادة PDF': 'Download certificate PDF',
  'ملف الشهادة قيد التجهيز': 'Certificate file is being prepared',
  'يمكن التحقق عبر الرابط أو رمز الشهادة.': 'You can verify using the link or certificate code.',
};
export function certificateCopy(locale: 'ar' | 'en', value: string): string {
  return locale === 'ar' ? value : (english[value] ?? value);
}

export function certificateStatusCopy(locale: 'ar' | 'en', value: string): string {
  const labels: Record<string, [string, string]> = {
    ACTIVE: ['نشطة', 'Active'],
    REVOKED: ['ملغاة', 'Revoked'],
    EXPIRED: ['منتهية', 'Expired'],
    REISSUED: ['مستبدلة', 'Reissued'],
    ARCHIVED: ['مؤرشفة', 'Archived'],
    DRAFT: ['مسودة', 'Draft'],
    PENDING_APPROVAL: ['بانتظار الاعتماد', 'Pending approval'],
    APPROVED: ['معتمدة', 'Approved'],
    SUSPENDED: ['معلقة', 'Suspended'],
    DEPRECATED: ['موقوفة تدريجيًا', 'Deprecated'],
    RETIRED: ['متقاعدة', 'Retired'],
    PERMANENT: ['دائمة', 'Permanent'],
    RENEWABLE: ['قابلة للتجديد', 'Renewable'],
    EXPIRING: ['محددة المدة', 'Time limited'],
  };
  return labels[value]?.[locale === 'ar' ? 0 : 1] ?? value;
}
