import {describe,it,expect} from 'vitest';
import {publicMajorProjection,assertMajorReviewCoverage,MAJOR_REVIEW_TEMPLATE,MajorNamingService} from '../../src';
const owner:any={id:'private',publicId:'MJR-1',slug:'computer-science',canonicalName:'Computer Science',displayName:'علوم الحاسوب',localizedNameAr:'علوم الحاسوب',localizedNameEn:'Computer Science',canonicalDedupKey:'private',optionalFields:{description:'Reviewed overview',reviewerEmail:'secret',metadata:{secret:'secret'},careerOutcomes:['Researcher',{private:'secret'}]},versions:[{rawContentBlocks:'secret'}],profiles:[{id:'published',level:'BACHELOR',status:'PUBLISHED',currentPublishedVersionId:'snapshot',metadata:{secret:true},degreeLevel:{private:true}},{id:'draft',status:'READY_TO_REVIEW',level:'MASTER'}]};
describe('P10 public exposure and required academic templates',()=>{
 it('does not expose raw source, unknown fields or future admin columns',()=>{const result=publicMajorProjection({...owner,futurePrivateColumn:'secret'});expect(JSON.stringify(result)).not.toContain('secret');expect(result).not.toHaveProperty('canonicalDedupKey');expect(result).not.toHaveProperty('versions');expect(result.profiles).toHaveLength(1);expect(result.profiles![0]).not.toHaveProperty('degreeLevel');});
 it('keeps reviewed AR/EN names and only string career entries',()=>{const result:any=publicMajorProjection(owner);expect(result.localizedNameAr).toBe('علوم الحاسوب');expect(result.localizedNameEn).toBe('Computer Science');expect(result.careerOutcomes).toEqual(['Researcher']);});
 it('excludes unreviewed sections and section metadata',()=>{const result=publicMajorProjection(owner,[{sectionKey:'approved',content:'Safe',reviewStatus:'APPROVED',metadata:{secret:true}},{sectionKey:'draft',content:'secret',reviewStatus:'NEEDS_REVIEW'}]);expect(result.contentSections).toEqual([{sectionKey:'approved',title:undefined,content:'Safe',reviewStatus:'APPROVED'}]);});
 it.each(['BACHELOR','MASTER','DOCTORATE'])('accepts a complete, owned %s coverage decision',level=>{const required=MAJOR_REVIEW_TEMPLATE[level];const sections=required.map((key,index)=>({id:String(index),content:key}));const coverage=Object.fromEntries(required.map((key,index)=>[key,String(index)]));expect(()=>assertMajorReviewCoverage(level,coverage,sections)).not.toThrow();});
 it('blocks one generic section masquerading as every required topic',()=>{const coverage=Object.fromEntries(MAJOR_REVIEW_TEMPLATE.BACHELOR.map(key=>[key,'one']));expect(()=>assertMajorReviewCoverage('BACHELOR',coverage,[{id:'one',content:'Generic'}])).toThrow('DISTINCT_SECTIONS');});
 it('rejects a foreign or empty covered section',()=>{const keys=MAJOR_REVIEW_TEMPLATE.MASTER;const coverage=Object.fromEntries(keys.map((key,index)=>[key,String(index)]));expect(()=>assertMajorReviewCoverage('MASTER',coverage,keys.map((_key,index)=>({id:String(index),content:index===2?'':'Reviewed'})))).toThrow('TEMPLATE_INCOMPLETE');});
 it('normalizes Arabic aliases without minting a second identity',()=>{expect(MajorNamingService.normalizeSearchText('هَنْدَسَة البرمجيّات')).toBe(MajorNamingService.normalizeSearchText('هندسه البرمجيات'));});
});
