import {describe,it,expect,vi} from 'vitest';
import {PrismaMajorRepository} from '../../src/majors/PrismaMajorRepository';
import {PrismaNewMajorCandidateRepository} from '../../src/majors/PrismaNewMajorCandidateRepository';
import {PrismaUniversityMajorResolutionWriter} from '../../src/universities/PrismaUniversityMajorResolutionWriter';
describe('P10 immutable publications and source reconciliation',()=>{
 it('rejects a stale revision under the database owner lock',async()=>{const db:any={major:{count:async()=>1},$queryRaw:vi.fn(async()=>[{revision:5n,status:'READY_TO_REVIEW'}])};await expect(new PrismaMajorRepository(db,false,true).lockForRevision('major',4)).rejects.toThrow('STALE_REVISION');expect(db.$queryRaw.mock.calls[0][0].join('')).toContain('FOR UPDATE');});
 it('does not expose a legacy root without an owned published snapshot',async()=>{const db:any={$queryRaw:vi.fn(async()=>[])};expect(await new PrismaMajorRepository(db).findPublishedSnapshot('legacy')).toBeNull();const sql=db.$queryRaw.mock.calls[0][0].join('');expect(sql).toContain('v."profileId"=p.id');expect(sql).toContain('p."currentPublishedVersionId"=s."versionId"');});
 it('uses immutable data and the same filter for list and count',async()=>{const db:any={$queryRaw:vi.fn().mockResolvedValueOnce([{versionId:'v1',payload:{publicId:'MJR-1',canonicalName:'Frozen',displayName:'Frozen',profiles:[]}}]).mockResolvedValueOnce([{total:1n}])};const result=await new PrismaMajorRepository(db).listPublished({search:"x' OR 1=1",limit:500});expect(result.pageSize).toBe(50);expect(result.data[0].displayName).toBe('Frozen');for(const [sql] of db.$queryRaw.mock.calls){expect(sql.text).toContain('MajorPublicationSnapshot');expect(sql.text).not.toContain("x' OR 1=1");expect(sql.values).toContain("x' OR 1=1");}});
 it('requires a transaction for source reconciliation',async()=>{await expect(new PrismaNewMajorCandidateRepository({} as any).resolve('NMC-1','major','digest')).rejects.toThrow('TRANSACTION_REQUIRED');});
 it('blocks stale source reconciliation before calling either owner writer',async()=>{const university:any={resolveProgramMajor:vi.fn()};const scholarship:any={resolveMajorReferences:vi.fn()};const repo=new PrismaNewMajorCandidateRepository({$queryRaw:async()=>[]} as any,university,scholarship,true);vi.spyOn(repo,'findByKey').mockResolvedValue({sourceDigest:'new'} as any);await expect(repo.resolve('NMC-1','major','old')).rejects.toThrow('STALE_SOURCE');expect(university.resolveProgramMajor).not.toHaveBeenCalled();expect(scholarship.resolveMajorReferences).not.toHaveBeenCalled();});
 it('guards the exact owner, label, degree and source timestamp during program linking',async()=>{const db:any={universityAcademicProgram:{updateMany:vi.fn(async()=>({count:1}))}};await new PrismaUniversityMajorResolutionWriter(db).resolveProgramMajor([{sourceType:'UNIVERSITY_PROGRAM',sourceId:'p',ownerId:'u',ownerDisplayName:'U',rawLabel:'Computer Science',degreeLevelId:'degree',sourceUpdatedAt:'2026-10-10T00:00:00.000Z',status:'DRAFT'}],'major');expect(db.universityAcademicProgram.updateMany.mock.calls[0][0].where.OR[0]).toMatchObject({id:'p',universityId:'u',sourceProgramName:'Computer Science',degreeLevelId:'degree',updatedAt:new Date('2026-10-10T00:00:00.000Z')});});
 it('handles an empty page while preserving the full queue count',async()=>{const db:any={$queryRaw:async()=>[{total:73,candidateKey:null}]};const result=await new PrismaNewMajorCandidateRepository(db).list({page:5});expect(result.total).toBe(73);expect(result.data).toEqual([]);});
 it('rejects unsupported source-set partial resolution',async()=>{const university:any={resolveProgramMajor:vi.fn()};const repo=new PrismaNewMajorCandidateRepository({$queryRaw:async()=>[]} as any,university,{} as any,true);vi.spyOn(repo,'findByKey').mockResolvedValue({sourceDigest:'same',sourcesTruncated:true} as any);await expect(repo.resolve('NMC-1','major','same')).rejects.toThrow('SOURCE_LIMIT_REVIEW_REQUIRED');expect(university.resolveProgramMajor).not.toHaveBeenCalled();});
});
