import { describe,it,expect,vi } from 'vitest';
import { PrismaReferenceOwnerReviewGateway } from '../../src/reference-data/PrismaReferenceOwnerReviewGateway';
import { PrismaReferenceDataRepository } from '../../src/reference-data/PrismaReferenceDataRepository';
import { readReferenceCodeUsage } from '../../src/reference-data/ReferenceCodeUsageInventory';
describe('P7 bounded owner persistence contracts',()=>{
 it('refuses unbound review locking and artifact verification',async()=>{const gateway=new PrismaReferenceOwnerReviewGateway({} as any);await expect(gateway.lock('id')).rejects.toThrow('TRANSACTION_REQUIRED');await expect(gateway.verifyArtifact('asset','a'.repeat(64))).rejects.toThrow('TRANSACTION_REQUIRED');});
 it('filters durable screening receipts by owner before exposing payload',async()=>{const db:any={importScreeningReceipt:{findUnique:async()=>({ownerDomain:'OTHER',result:{normalizedPayload:{secret:true}}})}};expect(await new PrismaReferenceOwnerReviewGateway(db).screening('id')).toBeNull();});
 it('uses a database CAS and never silently marks a stale plan applied',async()=>{const db:any={$executeRaw:vi.fn(async()=>0)};await expect(new PrismaReferenceOwnerReviewGateway(db).save({id:'plan',version:3,status:'APPLIED',preview:{},previewHash:'hash'} as any,2)).rejects.toThrow('REVIEW_CONFLICT');const statement=db.$executeRaw.mock.calls[0][0];expect(db.$executeRaw.mock.calls[0]).toContain(2);expect(statement[0]).toContain('UPDATE');});
 it('bounds the review list and does not interpolate malicious status into SQL text',async()=>{const db:any={$queryRaw:vi.fn(async()=>[])};const gateway=new PrismaReferenceOwnerReviewGateway(db);await expect(gateway.list(1001)).rejects.toThrow('PAGINATION_INVALID');await gateway.list(2,"x' OR 1=1");const fragments=db.$queryRaw.mock.calls[0][0];expect(fragments.join('')).not.toContain("x' OR 1=1");});
 it('applies source content with canonical ID and expected version inside the same owner transaction',async()=>{const spy=vi.spyOn(PrismaReferenceDataRepository.prototype,'upsertCountryInTransaction').mockResolvedValue({id:'stable'} as any);const gateway=new PrismaReferenceOwnerReviewGateway({} as any);const tx:any={boundaryId:'same',transactionClient:{}};await gateway.apply({entityType:'COUNTRY',payload:{iso2Code:'US',iso3Code:'USA',name:'United States'},preview:{currentId:'stable',currentVersion:4}} as any,tx,'actor');expect(spy).toHaveBeenCalledWith(expect.objectContaining({id:'stable',expectedVersion:4}),tx,'actor');spy.mockRestore();});
 it('counts scalar-code consumers with parameterized values and excludes FK-backed matches',async()=>{const db:any={$queryRaw:vi.fn().mockResolvedValueOnce([{code:'USD'}]).mockResolvedValueOnce([{key:'ReferenceCountry.defaultCurrencyCode',total:2n}])};expect(await readReferenceCodeUsage(db,'CURRENCY','canonical')).toEqual({'ReferenceCountry.defaultCurrencyCode':2});const sql=db.$queryRaw.mock.calls[1][0];expect(sql.text).toContain('IS NULL');expect(sql.values).toContain('USD');expect(sql.text).not.toContain('USD');});
 it('keeps updatedFrom/mapping filters in SQL with matching page/count predicates',async()=>{const db:any={$queryRaw:vi.fn().mockResolvedValueOnce([]).mockResolvedValueOnce([{total:1n}])};const repo=new PrismaReferenceDataRepository(db);const filters:any={mappingStatus:'UNMAPPED',updatedFrom:'2026-01-01T00:00:00.000Z',page:2,pageSize:25,activeOnly:true};await repo.listCountries(filters);expect(await repo.countRecords('countries',filters)).toBe(1);const list=db.$queryRaw.mock.calls[0][0],count=db.$queryRaw.mock.calls[1][0];expect(list.text).toContain('NOT (EXISTS');expect(list.text).toContain('LIMIT');expect(count.text).toContain('NOT (EXISTS');expect(list.values).toContain(25);});
});
