import {describe,it,expect,vi} from 'vitest';import express from 'express';import request from 'supertest';
vi.mock('../../../../src/presentation/security/SecurityMiddlewareFactory.js',()=>({SecurityMiddlewareFactory:{createAdminPermissionGuard:(permission:string)=>(req:any,res:any,next:any)=>{if(!req.authUserId)return res.status(401).json({code:'AUTH_REQUIRED'});if(req.get('X-Deny-Permission')===permission)return res.status(403).json({code:'PERMISSION_DENIED'});next();}}}));
import {InternationalTestAdminRouter} from '../../../../src/presentation/api/router/InternationalTestAdminRouter';
function harness(){const uc:any={publish:vi.fn(),verifySource:vi.fn(),createTest:vi.fn(),manualNames:vi.fn(),govern:vi.fn(),get:vi.fn(async()=>({id:'test',revision:7}))};const app=express();app.use(express.json());app.use((req:any,_res,next)=>{if(req.get('X-Actor'))req.authUserId=req.get('X-Actor');next();});app.use('/tests',InternationalTestAdminRouter.create({internationalTestAdminUseCases:uc,crossDomainGraphReadService:{} as any}));return {app,uc};}
describe('P9 HTTP protection and errors',()=>{
 it('refuses unauthenticated publishing',async()=>{const h=harness();expect((await request(h.app).post('/tests/test/publish').send({reason:'review'})).status).toBe(401);expect(h.uc.publish).not.toHaveBeenCalled();});
 it('requires separate publication permission',async()=>{const h=harness();expect((await request(h.app).post('/tests/test/publish').set('X-Actor','editor').set('X-Deny-Permission','admin:international-tests:publish').set('If-Match','7').send({reason:'review'})).status).toBe(403);});
 it('requires the caller revision, passes only the server actor, and rejects forged actor',async()=>{const h=harness();expect((await request(h.app).post('/tests/test/publish').set('X-Actor','publisher').send({reason:'review'})).status).toBe(400);expect((await request(h.app).post('/tests/test/publish').set('X-Actor','publisher').set('If-Match','"7"').send({reason:'review',actorId:'forged'})).status).toBe(400);const result=await request(h.app).post('/tests/test/publish').set('X-Actor','publisher').set('If-Match','"7"').send({reason:'review'});expect(result.status).toBe(200);expect(h.uc.publish).toHaveBeenCalledWith('test',expect.objectContaining({actorId:'publisher',expectedRevision:7,reason:'review'}));});
 it('returns a stable conflict and sanitized unexpected persistence failures',async()=>{const h=harness();h.uc.publish.mockRejectedValueOnce(new Error('INTERNATIONAL_TEST_APPROVAL_STALE')).mockRejectedValueOnce(new Error('postgres password=secret'));const first=await request(h.app).post('/tests/test/publish').set('X-Actor','publisher').set('If-Match','7').send({reason:'review'});expect(first.status).toBe(409);const second=await request(h.app).post('/tests/test/publish').set('X-Actor','publisher').set('If-Match','7').send({reason:'review'});expect(second.status).toBe(500);expect(JSON.stringify(second.body)).not.toContain('secret');});
 it('refuses create publication bypass and self-reported verification',async()=>{const h=harness();for(const payload of [{canonicalName:'Exam',providerName:'Provider',testCategory:'OTHER',status:'PUBLISHED'},{canonicalName:'Exam',providerName:'Provider',testCategory:'OTHER',isSourceVerified:true}])expect((await request(h.app).post('/tests').set('X-Actor','editor').send(payload)).status).toBe(400);expect(h.uc.createTest).not.toHaveBeenCalled();});
});
