import {describe,it,expect,vi} from 'vitest';import express from 'express';import request from 'supertest';
vi.mock('../../../../src/presentation/security/SecurityMiddlewareFactory.js',()=>({SecurityMiddlewareFactory:{createAdminPermissionGuard:(permission:string)=>(req:any,res:any,next:any)=>{if(!req.authUserId)return res.status(401).json({code:'AUTH_REQUIRED'});if(req.get('X-Deny-Permission')===permission)return res.status(403).json({code:'PERMISSION_DENIED'});next();}}}));
import {MajorAdminRouter} from '../../../../src/presentation/api/router/MajorAdminRouter';
function harness(){const uc:any={publish:vi.fn(),getMajor:vi.fn(async()=>({id:'major',revision:8})),approveNewMajorCandidate:vi.fn(async()=>({type:'CREATED'})),rejectNewMajorCandidate:vi.fn(),reviewWorkingVersion:vi.fn()};const app=express();app.use(express.json());app.use((req:any,_res,next)=>{if(req.get('X-Actor'))req.authUserId=req.get('X-Actor');next();});app.use('/majors',MajorAdminRouter.create({adminMajorUseCases:uc}));return {app,uc};}
describe('P10 server authority and command contracts',()=>{
 it('refuses publishing without authentication',async()=>{const h=harness();expect((await request(h.app).post('/majors/major/publish').send({reason:'Reviewed'})).status).toBe(401);expect(h.uc.publish).not.toHaveBeenCalled();});
 it('requires separate publication permission',async()=>{const h=harness();expect((await request(h.app).post('/majors/major/publish').set('X-Actor','editor').set('X-Deny-Permission','admin:majors:publish').set('If-Match','7').send({reason:'Reviewed'})).status).toBe(403);});
 it('passes the authenticated reviewer and caller revision only',async()=>{const h=harness();const result=await request(h.app).post('/majors/major/publish').set('X-Actor','real').set('If-Match','"7"').send({reason:'Reviewed'});expect(result.status).toBe(200);expect(h.uc.publish).toHaveBeenCalledWith('major',expect.objectContaining({actorId:'real',expectedRevision:7,reason:'Reviewed'}));expect(result.headers['x-entity-revision']).toBe('8');});
 it('rejects a forged actor or missing revision',async()=>{const h=harness();expect((await request(h.app).post('/majors/major/publish').set('X-Actor','real').set('If-Match','7').send({reason:'Reviewed',actorId:'fake'})).status).toBe(400);expect((await request(h.app).post('/majors/major/publish').set('X-Actor','real').send({reason:'Reviewed'})).status).toBe(422);expect(h.uc.publish).not.toHaveBeenCalled();});
 it('requires owner permissions before reconciling university or scholarship references',async()=>{const h=harness();expect((await request(h.app).post('/majors/new-candidates/NMC-1/approve').set('X-Actor','reviewer').set('X-Deny-Permission','admin:universities:manage').send({})).status).toBe(403);expect(h.uc.approveNewMajorCandidate).not.toHaveBeenCalled();});
 it('rejects candidate decisions without a source digest',async()=>{const h=harness();expect((await request(h.app).post('/majors/new-candidates/NMC-1/reject').set('X-Actor','reviewer').send({reason:'Not a major'})).status).toBe(400);expect(h.uc.rejectNewMajorCandidate).not.toHaveBeenCalled();});
 it('sanitizes persistence failures and reports stale revision as conflict',async()=>{const h=harness();h.uc.publish.mockRejectedValueOnce(new Error('password=secret')).mockRejectedValueOnce(new Error('MAJOR_STALE_REVISION'));const first=await request(h.app).post('/majors/major/publish').set('X-Actor','real').set('If-Match','7').send({reason:'Reviewed'});expect(first.status).toBe(500);expect(JSON.stringify(first.body)).not.toContain('secret');const second=await request(h.app).post('/majors/major/publish').set('X-Actor','real').set('If-Match','7').send({reason:'Reviewed'});expect(second.status).toBe(409);});
});
