import { describe, it, expect, vi } from 'vitest';
import { ReferenceOwnerReviewUseCases } from '../../src/reference-data/use-cases/ReferenceOwnerReviewUseCases';
import { referenceImportPayloadDigest } from '../../src/reference-data/services/ReferenceDataScreeningHandoffConsumer';
import { AtomicDomainMutationCoordinator } from '../../src/event-foundation/use-cases/AtomicDomainMutationCoordinator';
import { AtomicAuditedOutboxMutationExecutor } from '../../src/event-foundation/use-cases/AtomicAuditedOutboxMutationExecutor';
const actor = { actorId:'reviewer' };
async function harness() {
  const payload = {iso2Code:'US',iso3Code:'USA',name:'United States'};
  const result = {state:'NEEDS_OWNER_REVIEW',entityType:'COUNTRY',dryRun:false,normalizedPayload:payload,normalizedPayloadHash:referenceImportPayloadDigest(payload),sourceArtifactId:'asset',sourceContentHash:'a'.repeat(64),issues:[]};
  const state = {plans:new Map<string,any>(),snapshots:new Map<string,any>(),writes:0,audits:0,events:0};
  let revision=1; let source='source'; let fail=false;
  const gateway:any = {withTransaction:()=>gateway,lock:vi.fn(),screening:async()=>({requestHash:source,result}),verifyArtifact:vi.fn(async()=>{}),
    inspect:async()=>({issues:[],currentId:'stable',currentVersion:revision,dependencyHash:'dependencies'}), get:async(id:string)=>state.plans.get(id)??null,
    create:async(plan:any)=>state.plans.set(plan.id,JSON.parse(JSON.stringify(plan))),save:async(plan:any,version:number)=>{if(state.plans.get(plan.id)?.version!==version) throw Error('REFERENCE_OWNER_REVIEW_CONFLICT');state.plans.set(plan.id,JSON.parse(JSON.stringify(plan)));},
    apply:async()=>{state.writes++;return {id:'stable'};},list:async()=>({data:[...state.plans.values()],total:state.plans.size}),
    snapshots:async()=>({data:[...state.snapshots.values()],total:state.snapshots.size}),reviewedSnapshots:async()=>[...state.snapshots.values()].filter(row=>row.status==='REVIEWED'),snapshot:async(id:string)=>state.snapshots.get(id)??null,
    saveSnapshot:async(row:any,version?:number)=>{if(version!==undefined&&state.snapshots.get(row.snapshotId)?.version!==version)throw Error('REFERENCE_OWNER_REVIEW_CONFLICT');state.snapshots.set(row.snapshotId,structuredClone(row));}};
  const executor = new AtomicAuditedOutboxMutationExecutor({execute:async(work:any)=>{ const before=structuredClone(state);try{return await work({boundaryId:'tx'});}catch(error){Object.assign(state,before);throw error;}}} as any,
    {saveInTransaction:async()=>{state.audits++;}} as any,{appendInTransaction:async()=>{if(fail)throw Error('OUTBOX_FAILED');state.events++;}} as any);
  const cases = new ReferenceOwnerReviewUseCases(gateway,new AtomicDomainMutationCoordinator(executor));
  return {cases,state,gateway,result,bump:()=>revision++,sourceChange:()=>source='changed',fail:()=>fail=true};
}
async function approved(h:Awaited<ReturnType<typeof harness>>) { const p=await h.cases.preview('receipt',actor);return h.cases.review(p.id,{expectedVersion:p.version,previewHash:p.previewHash,decision:'APPROVE',reason:'Reviewed source'},actor); }
const source:any = {standardFamily:'ISO_3166',sourceAuthority:'Official authority',sourceVersion:'2026',sourceArtifactHash:'a'.repeat(64),sourceArtifactId:'asset',sourceUrl:'https://example.org/source',retrievedAt:'2026-01-01T00:00:00.000Z'};
describe('P7 durable owner import and standards closeout',()=>{
 it('requires an authenticated owner before touching receipt persistence',async()=>{const h=await harness();await expect(h.cases.preview('receipt',{actorId:''})).rejects.toThrow('ACTOR_REQUIRED');expect(h.gateway.lock).not.toHaveBeenCalled();});
 it('creates one durable preview without duplicate owner audit/events on replay',async()=>{const h=await harness();const p=await h.cases.preview('receipt',actor);expect(await h.cases.preview('receipt',actor)).toEqual(p);expect(h.state.events).toBe(1);expect(h.state.writes).toBe(0);expect(h.gateway.verifyArtifact).toHaveBeenCalledWith('asset','a'.repeat(64));});
 it('refuses legacy receipts without payload and dry-run receipts',async()=>{for(const field of ['normalizedPayload','dryRun']){const h=await harness();(h.result as any)[field]=undefined;await expect(h.cases.preview('receipt',actor)).rejects.toThrow('SCREENING_EVIDENCE_REQUIRED');expect(h.state.plans.size).toBe(0);}});
 it('rejects tampered source payload digest',async()=>{const h=await harness();h.result.normalizedPayload.name='Forged';await expect(h.cases.preview('receipt',actor)).rejects.toThrow('SOURCE_CONFLICT');});
 it('requires real source artifact trust before preview',async()=>{const h=await harness();h.gateway.verifyArtifact.mockRejectedValueOnce(Error('SOURCE_HASH_CONFLICT'));await expect(h.cases.preview('receipt',actor)).rejects.toThrow('SOURCE_HASH_CONFLICT');expect(h.state.plans.size).toBe(0);});
 it('cannot apply a merely screened or previewed record',async()=>{const h=await harness();const p=await h.cases.preview('receipt',actor);await expect(h.cases.apply(p.id,{expectedVersion:p.version,previewHash:p.previewHash},actor)).rejects.toThrow('APPROVAL_REQUIRED');expect(h.state.writes).toBe(0);});
 it('applies reviewed canonical content only once and skips duplicate audit/outbox',async()=>{const h=await harness();const p=await approved(h);const before=h.state.events;expect(await h.cases.apply(p.id,{expectedVersion:p.version,previewHash:p.previewHash},actor)).toEqual({id:'stable'});expect(await h.cases.apply(p.id,{expectedVersion:p.version,previewHash:p.previewHash},actor)).toEqual({id:'stable'});expect(h.state.writes).toBe(1);expect(h.state.events).toBe(before+1);});
 it('rejects stale dependency revisions and refresh cancels approval',async()=>{const h=await harness();const p=await approved(h);h.bump();await expect(h.cases.apply(p.id,{expectedVersion:p.version,previewHash:p.previewHash},actor)).rejects.toThrow('STALE_PREVIEW');const refreshed=await h.cases.refresh(p.id,p.version,actor);expect(refreshed.status).toBe('PREVIEWED');expect(refreshed.reviewer).toBeNull();expect(refreshed.previewHash).not.toBe(p.previewHash);expect(h.state.writes).toBe(0);});
 it('rejects changed receipt request identity',async()=>{const h=await harness();const p=await approved(h);h.sourceChange();await expect(h.cases.apply(p.id,{expectedVersion:p.version,previewHash:p.previewHash},actor)).rejects.toThrow('STALE_PREVIEW');});
 it('rolls back canonical write and applied receipt on outbox failure',async()=>{const h=await harness();const p=await approved(h);h.fail();await expect(h.cases.apply(p.id,{expectedVersion:p.version,previewHash:p.previewHash},actor)).rejects.toThrow('OUTBOX_FAILED');expect(h.state.writes).toBe(0);expect(h.state.plans.get(p.id).status).toBe('APPROVED');});
 it('never auto-approves a standards source and uses actual persisted readiness',async()=>{const h=await harness();const row=await h.cases.createSnapshot(source,actor);expect(row.status).toBe('DRAFT');expect((await h.cases.readiness())[0].readiness).toBe('MISSING_REVIEWED_SNAPSHOT');const reviewed=await h.cases.reviewSnapshot(row.snapshotId,row.version,'APPROVE','Verified official version',actor);expect(reviewed.reviewedBy).toBe(actor.actorId);expect((await h.cases.readiness())[0].sourceVersion).toBe('2026');});
 it('requires explicit supersession of a previous approved standards version',async()=>{const h=await harness();const row=await h.cases.createSnapshot(source,actor);await h.cases.reviewSnapshot(row.snapshotId,row.version,'APPROVE','Verified version',actor);const next=await h.cases.createSnapshot({...source,sourceVersion:'2027'},actor);await expect(h.cases.reviewSnapshot(next.snapshotId,next.version,'APPROVE','New version',actor)).rejects.toThrow('SUPERSESSION_CONFLICT');const replacing=await h.cases.createSnapshot({...source,sourceVersion:'2027',supersedesSnapshotId:row.snapshotId},actor);await h.cases.reviewSnapshot(replacing.snapshotId,replacing.version,'APPROVE','New official version',actor);expect(h.state.snapshots.get(row.snapshotId).status).toBe('SUPERSEDED');expect((await h.cases.readiness())[0].sourceVersion).toBe('2027');});
 it('never grants source approval without verified artifact hash',async()=>{const h=await harness();h.gateway.verifyArtifact.mockRejectedValueOnce(Error('BAD_ARTIFACT'));await expect(h.cases.createSnapshot(source,actor)).rejects.toThrow('BAD_ARTIFACT');expect(h.state.snapshots.size).toBe(0);});
});
